# Generated by Django 3.0.4 on 2020-05-22 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backlog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='elapsedTime',
            field=models.CharField(blank=True, max_length=255, verbose_name='elapsedTime'),
        ),
    ]
