# Generated by Django 2.0.4 on 2020-05-28 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_code', models.CharField(max_length=255, verbose_name='code')),
                ('post_time', models.CharField(max_length=255, verbose_name='postTime')),
                ('message', models.CharField(blank=True, max_length=255, verbose_name='message')),
            ],
        ),
    ]
