# Generated by Django 2.0.4 on 2020-05-31 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slack', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='slack_comment_id',
            field=models.CharField(blank=True, max_length=255, verbose_name='message'),
        ),
    ]
