# Generated by Django 2.0.4 on 2020-05-31 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slack', '0002_message_slack_comment_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='message',
            field=models.TextField(blank=True, max_length=50000, verbose_name='message'),
        ),
    ]
