# Generated by Django 2.0.4 on 2020-05-31 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slack', '0003_auto_20200531_0939'),
    ]

    operations = [
        migrations.CreateModel(
            name='SlackMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='名前')),
                ('slack_name', models.CharField(max_length=255, verbose_name='slack名')),
                ('slack_id', models.CharField(max_length=255, verbose_name='slackId')),
            ],
        ),
    ]
