# Generated by Django 2.0.4 on 2020-06-01 08:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('slack', '0005_slackmember_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='部署名')),
            ],
        ),
        migrations.AlterField(
            model_name='slackmember',
            name='status',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='ステータス'),
        ),
        migrations.AddField(
            model_name='slackmember',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='slack.Department', verbose_name='部署'),
        ),
    ]
