# Generated by Django 2.0.4 on 2020-06-01 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slack', '0006_auto_20200601_0801'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='branch',
            field=models.IntegerField(blank=True, choices=[('10', '本社'), ('20', '滋賀支店'), ('30', '舞鶴支店')], null=True, verbose_name='支店'),
        ),
    ]
