# Generated by Django 2.0.4 on 2020-06-01 17:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('slack', '0007_department_branch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='branch',
            field=models.IntegerField(blank=True, choices=[(10, '本社'), (20, '滋賀支店'), (30, '舞鶴支店')], null=True, verbose_name='支店'),
        ),
        migrations.AlterField(
            model_name='slackmember',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='department_name', to='slack.Department', verbose_name='部署'),
        ),
    ]
