# Generated by Django 2.0.4 on 2020-06-01 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slack', '0008_auto_20200601_1740'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='encode_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='postTimes'),
        ),
    ]
