# Generated by Django 2.0.4 on 2020-06-02 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slack', '0009_message_encode_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='slackmember',
            name='update_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='投稿時間'),
        ),
    ]
