# Generated by Django 2.0.4 on 2020-06-18 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slack', '0011_events'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slackmember',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='アカウント'),
        ),
    ]
