# Generated by Django 2.0.4 on 2020-06-18 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slack', '0012_auto_20200618_2057'),
    ]

    operations = [
        migrations.AddField(
            model_name='slackmember',
            name='account',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='アカウント'),
        ),
        migrations.AlterField(
            model_name='slackmember',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='名前'),
        ),
    ]
