# Generated by Django 2.0.4 on 2020-06-19 14:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('slack', '0013_auto_20200618_2059'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat_number', models.CharField(blank=True, max_length=255, null=True, verbose_name='座席番号')),
                ('eventDate', models.DateField(blank=True, max_length=255, null=True, verbose_name='eventDate')),
                ('user_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_name', to='slack.SlackMember', verbose_name='社員Id')),
            ],
        ),
    ]
