# Generated by Django 2.0.4 on 2020-06-19 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slack', '0014_seat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seat',
            name='user_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='社員Id'),
        ),
    ]
