# Generated by Django 2.0.4 on 2020-06-03 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userId', models.CharField(max_length=255, verbose_name='code')),
                ('start_time', models.TimeField(blank=True, null=True, verbose_name='startTime')),
                ('end_time', models.TimeField(blank=True, null=True, verbose_name='endTime')),
                ('startDate', models.DateField(blank=True, null=True, verbose_name='startDate')),
                ('comment', models.TextField(blank=True, max_length=5000, null=True, verbose_name='comment')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='title')),
                ('status', models.IntegerField(blank=True, choices=[(10, '仮登録'), (20, '確定')], default=10, null=True, verbose_name='ステータス')),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='名前')),
                ('user_code', models.CharField(blank=True, max_length=255, null=True, verbose_name='社員コード')),
                ('employment_status', models.IntegerField(blank=True, choices=[(10, '正社員'), (20, 'パート'), (30, 'アルバイト')], null=True, verbose_name='雇用形態')),
                ('comment', models.TextField(blank=True, max_length=5000, null=True, verbose_name='comment')),
            ],
        ),
    ]
